import "./globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import { HeroImage } from "@/components/HeroImage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    // title: "Create Next App",
    title: "chords list",
    // description: "Generated by create next app",
    description: "list of guitar chords for famous kurdish and arabic songs",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className} dark:bg-slate-800`}>
                <Navbar />
                <HeroImage />
                {children}
            </body>
        </html>
    );
}
